# Generated by Django 3.1.2 on 2020-12-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201228_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='S'),
            preserve_default=False,
        ),
    ]
